---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    target-branch: master
    assignees:
      - danner26
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    target-branch: master
    assignees:
      - danner26
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    target-branch: master
    assignees:
      - danner26
