manufacturer: HP
model: ProDesk 400 G6 MT
slug: hpe-prodesk-400-g6-mt
part_number: 8DS76PA
u_height: 0
is_full_depth: false
weight: 5.47
weight_unit: kg
comments: '[HP ProDesk 400 G6 Microtower PC (8DS76PA) - All Tech Specs](https://www.hp.com/lk-en/products/desktops/product-details/product-specifications/30927632)'
power-ports:
  - name: PSU
    type: iec-60320-c14
    maximum_draw: 180
interfaces:
  - name: ETH-1
    type: 1000base-t
