---
manufacturer: HP
model: ProDesk 400 G4 SFF
slug: hpe-prodesk-400-g4-sff
part_number: 3SW63UC
u_height: 6.5
is_full_depth: false
weight: 4.6
weight_unit: kg
comments: '[HP ProDesk 400 G4 Small Form Factor PC (3SW63UC) - All Tech Specs](https://support.hp.com/ca-en/product/product-specs/hp-prodesk-400-g4-small-form-factor-pc/model/15292381?sku=3sw63uc)'
power-ports:
  - name: PSU
    type: iec-60320-c14
    maximum_draw: 180
interfaces:
  - name: ETH-1
    type: 1000base-t
module-bays:
  - name: pcie-0
    position: '0'
  - name: pcie-1
    position: '1'
